// <auto-generated />
using System;
using DMO.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DMO_Model.Migrations
{
    [DbContext(typeof(MediaMetaDatabaseContext))]
    partial class MediaMetaDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("DMO_Model.Models.Label", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("MediaMetaJsonID");

                    b.Property<string>("Name");

                    b.Property<float>("Probability");

                    b.HasKey("ID");

                    b.HasIndex("MediaMetaJsonID");

                    b.ToTable("Label");
                });

            modelBuilder.Entity("DMO_Model.Models.MediaMetaJson", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Json");

                    b.HasKey("ID");

                    b.ToTable("MediaMetaJsons");
                });

            modelBuilder.Entity("DMO_Model.Models.Label", b =>
                {
                    b.HasOne("DMO_Model.Models.MediaMetaJson")
                        .WithMany("Labels")
                        .HasForeignKey("MediaMetaJsonID");
                });
#pragma warning restore 612, 618
        }
    }
}
